### ISSUE TITLE
Pod Folder Missing

### ISSUE THREAD

**Issue by wellkunnected** [wbaumann/SmartReceiptsiOS#301]
Where is the Pods File Folder? I can see the Pods file but its missing the folder to run the app opening the workspace.

**Comment by wbaumann** [comment]
Hi,

We chose to not include the `Pods` directory in the main source of the project, since we felt that it was adding a lot of noise to any commit that updated the `Podfile`. This SO breakdown describes what must be in there vs what is optional:

- https://stackoverflow.com/a/22323702/4250037

So we decided against including that. 

Once you pull down the source, you can fetch the `Pods` directory by running `pod install`. Does that work?

**Comment by wbaumann** [comment]
Have you installed [cocoapods](https://cocoapods.org/) on your machine? If so, you should be able to run the following two commands in your cloned directory:

```
pod repo update
pod install
```

Afterwards, try to launch XCode and let me know if that fixes it

**Comment by wbaumann** [comment]
Note: You also need to import the `xcworkspace` to find the project (for use with Pods)

**Comment by wbaumann** [comment]
Closing as this is now outdated. Feel free to re-open if you need help
